name: Build and lint code
description: Action that installs dependencies, builds and lints the code
on:
  pull_request:
    types: [synchronize, opened]
jobs:
  build-and-lint-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'
      - name: Enable Corepack
        run: corepack enable
      - name: Install modules
        run: yarn install --immutable
      - name: Build code
        run: yarn build
      - name: Biome check
        run: yarn lint
